parameters:
  signSteps: []

steps:
- task: DotNetCoreCLI@2  
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- script: nbgv cloud
  displayName: Set Version
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- powershell: |
    mkdir $Env:Temp\Packages -Force
  displayName: Build

- task: DotNetCoreCLI@2
  inputs:
    command: pack
    packagesToPack: Source/MSBuild.Sdk.Extras/MSBuild.Sdk.Extras.csproj
    configuration: $(BuildConfiguration)
    packDirectory: $(Build.ArtifactStagingDirectory)\Packages    
    verbosityPack: Minimal
  displayName: Build Package

- ${{ parameters.signSteps }}

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Package
