queue:
  name: Hosted VS2017
  
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables
    

- powershell: |
    mkdir $Env:Temp\packages
    msbuild /restore /t:pack /p:PackageOutputPath=.\artifacts
  displayName: Build

- task: CopyFiles@2
  inputs:
    Contents: 'artifacts/MSBuild.Sdk.Extras.*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)\Packages'    

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Packages
    artifactType: container
    artifactName: Package