queue:
  name: Hosted VS2017
  
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables
    

- powershell: |
    msbuild /restore /t:pack /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)\Package
  displayName: Build

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)\Package
    artifactType: container
    artifactName: Package